// Generated by ts-to-zod
import type { output } from "./zod.ts";
import { z } from "./zod.ts";
import { brandingSchema } from "./branding.ts";

const adTargetParamSchema = z.object({
  name: z.string(),
  value: z.union([z.string(), z.array(z.string())]),
});

const editionCommercialPropertiesSchema = z.object({
  adTargeting: z.array(adTargetParamSchema),
  branding: brandingSchema.optional(),
});

export type ZCommercialProperties = output<typeof commercialPropertiesSchema>;
export const commercialPropertiesSchema = z.object({
  UK: editionCommercialPropertiesSchema,
  US: editionCommercialPropertiesSchema,
  AU: editionCommercialPropertiesSchema,
  INT: editionCommercialPropertiesSchema,
});
